spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: root
    password: 123456
  jpa:
    # true: ????? ???? ??? ????? ????.
    # false: ????? ??? ? ??? ????? ????.
    open-in-view: true  # true:???
    hibernate:
      # create: ??? ???? drop?? ?? ???? ?. ??????? ???? ??? drop? create? ????.
      # update: ??? ???? ?? ?? ?? ????? ??? ??? ??. ???? ???? ??? ???? ?? ???? ??????.
      ddl-auto: update
      naming:
        # ???(???)? ?? ? ??? ??? ??? ??(??)? ???.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # ???? sql ???? ??
    properties:
      hibernate.format_sql: true # sql???? ?? ?? ????.
